CREATE TABLE IF NOT EXISTS xhs_note (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  note_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '小红书笔记ID',
  note_url VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '采集时的笔记地址',
  source_account_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次采集使用的账号备注名',
  total_comment_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '页面展示的评论总数',
  collected_comment_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次实际采集的评论数量',
  first_collected_at BIGINT NOT NULL DEFAULT 0 COMMENT '首次采集时间(Unix秒)',
  last_collected_at BIGINT NOT NULL DEFAULT 0 COMMENT '最近采集时间(Unix秒)',
  created_at BIGINT NOT NULL DEFAULT 0 COMMENT '记录创建时间(Unix秒)',
  updated_at BIGINT NOT NULL DEFAULT 0 COMMENT '记录更新时间(Unix秒)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_note_id (note_id),
  KEY idx_source_account_last_collected_at (source_account_name, last_collected_at),
  KEY idx_last_collected_at (last_collected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小红书笔记评论采集记录表';

CREATE TABLE IF NOT EXISTS xhs_note_comment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  note_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所属小红书笔记ID',
  comment_key VARCHAR(300) NOT NULL DEFAULT '' COMMENT '评论唯一键，未公开真实ID时使用DOM内容生成',
  platform_comment_id VARCHAR(255) NOT NULL DEFAULT '' COMMENT '页面暴露的小红书评论ID',
  parent_comment_key VARCHAR(300) NOT NULL DEFAULT '' COMMENT '父评论唯一键',
  parent_platform_comment_id VARCHAR(255) NOT NULL DEFAULT '' COMMENT '父评论的小红书评论ID',
  user_id VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论用户ID',
  user_name VARCHAR(120) NOT NULL DEFAULT '' COMMENT '评论用户名',
  content TEXT NOT NULL COMMENT '评论正文',
  publish_time VARCHAR(80) NOT NULL DEFAULT '' COMMENT '页面展示的评论发布时间',
  location VARCHAR(80) NOT NULL DEFAULT '' COMMENT '页面展示的评论地区',
  like_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数',
  reply_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '直接回复数量',
  reply_to_user_id VARCHAR(255) NOT NULL DEFAULT '' COMMENT '引用回复的用户ID',
  reply_to_user_name VARCHAR(120) NOT NULL DEFAULT '' COMMENT '引用回复的用户名',
  is_reply TINYINT NOT NULL DEFAULT 0 COMMENT '是否楼中楼回复: 0否 1是',
  is_author TINYINT NOT NULL DEFAULT 0 COMMENT '是否笔记作者: 0否 1是',
  first_collected_at BIGINT NOT NULL DEFAULT 0 COMMENT '首次采集时间(Unix秒)',
  last_collected_at BIGINT NOT NULL DEFAULT 0 COMMENT '最近采集时间(Unix秒)',
  created_at BIGINT NOT NULL DEFAULT 0 COMMENT '记录创建时间(Unix秒)',
  updated_at BIGINT NOT NULL DEFAULT 0 COMMENT '记录更新时间(Unix秒)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_note_comment_key (note_id, comment_key),
  KEY idx_note_parent_key (note_id, parent_comment_key),
  KEY idx_note_parent_platform_id (note_id, parent_platform_comment_id),
  KEY idx_note_last_collected_at (note_id, last_collected_at),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小红书笔记评论采集明细表';
